image: docker:27.4.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LIB_PATH: 'root/utils-library'
  VERSION: '1.1'
  IMAGE_TAG: "${VERSION}.${CI_PIPELINE_IID}-${CI_COMMIT_REF_NAME}"
  TELEGRAM_CHAT_ID: '1021912706'
  DOCKER_BUILDKIT: "0"

build:
  stage: build
  only:
      - test
      - main

  before_script:
    - docker info
    - apk add --no-cache curl

  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker logout $CI_REGISTRY
    - |
      curl $WEBHOOK_URL \
      -X POST \
      -H 'Content-type: application/json' \
      -H 'Accept: application/json' \
      -H "Authorization: $WEBHOOK_TOKEN" \
      --data "$FLUX_NOTIFICATION_DATA"
