"""initial schema

Revision ID: e5d5bf9e6564
Revises: 
Create Date: 2026-10-01 14:10:45.656856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5d5bf9e6564'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_unit', sa.String(length=3), nullable=False),
    sa.Column('venue_slug', sa.Text(), nullable=False),
    sa.Column('search_q', sa.Text(), nullable=False),
    sa.Column('match_re', sa.Text(), nullable=False),
    sa.Column('exclude_re', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("base_unit in ('g', 'ml', 'pcs')", name=op.f('ck_product_base_unit')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_product'))
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('portions', sa.Integer(), server_default='2', nullable=False),
    sa.Column('appliance', sa.String(length=16), server_default='stove', nullable=False),
    sa.Column('batch_note', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("appliance in ('stove', 'air_fryer', 'none')", name=op.f('ck_recipe_appliance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe')),
    sa.UniqueConstraint('slug', name=op.f('uq_recipe_slug'))
    )
    op.create_table('wolt_order',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('venue_name', sa.Text(), server_default='', nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wolt_order'))
    )
    op.create_table('meal_plan',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(length=16), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Numeric(asdecimal=False), server_default='1', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('cooked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("meal in ('breakfast', 'lunch', 'dinner')", name=op.f('ck_meal_plan_meal')),
    sa.CheckConstraint('multiplier > 0', name=op.f('ck_meal_plan_multiplier_positive')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_meal_plan_recipe_id_recipe'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('day', 'meal', name=op.f('pk_meal_plan'))
    )
    op.create_table('pantry_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('order', 'manual', 'cooked', 'correction')", name=op.f('ck_pantry_entry_source')),
    sa.ForeignKeyConstraint(['product_key'], ['product.key'], name=op.f('fk_pantry_entry_product_key_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pantry_entry'))
    )
    op.create_index(op.f('ix_pantry_entry_product_key'), 'pantry_entry', ['product_key'], unique=False)
    op.create_index('uq_pantry_entry_ref_product', 'pantry_entry', ['ref', 'product_key'], unique=True, postgresql_where=sa.text('ref is not null'))
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('product_key', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('unit', sa.String(length=3), nullable=True),
    sa.Column('text_amount', sa.Text(), server_default='', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("unit in ('g', 'ml', 'pcs')", name=op.f('ck_recipe_ingredient_unit')),
    sa.ForeignKeyConstraint(['product_key'], ['product.key'], name=op.f('fk_recipe_ingredient_product_key_product')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_ingredient_recipe_id_recipe'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredient'))
    )
    op.create_index(op.f('ix_recipe_ingredient_recipe_id'), 'recipe_ingredient', ['recipe_id'], unique=False)
    op.create_table('recipe_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('heat', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint('timer_seconds > 0', name=op.f('ck_recipe_step_timer_positive')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_step_recipe_id_recipe'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_step'))
    )
    op.create_index(op.f('ix_recipe_step_recipe_id'), 'recipe_step', ['recipe_id'], unique=False)
    op.create_table('wolt_item',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('venue_slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('product_key', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('pack_amount', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('weight_step_g', sa.Integer(), nullable=True),
    sa.Column('preferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_key'], ['product.key'], name=op.f('fk_wolt_item_product_key_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wolt_item'))
    )
    op.create_index(op.f('ix_wolt_item_product_key'), 'wolt_item', ['product_key'], unique=False)
    op.create_table('wolt_order_item',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wolt_item_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('count', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('grams', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('product_key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['wolt_order.id'], name=op.f('fk_wolt_order_item_order_id_wolt_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_key'], ['product.key'], name=op.f('fk_wolt_order_item_product_key_product')),
    sa.PrimaryKeyConstraint('order_id', 'position', name=op.f('pk_wolt_order_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wolt_order_item')
    op.drop_index(op.f('ix_wolt_item_product_key'), table_name='wolt_item')
    op.drop_table('wolt_item')
    op.drop_index(op.f('ix_recipe_step_recipe_id'), table_name='recipe_step')
    op.drop_table('recipe_step')
    op.drop_index(op.f('ix_recipe_ingredient_recipe_id'), table_name='recipe_ingredient')
    op.drop_table('recipe_ingredient')
    op.drop_index('uq_pantry_entry_ref_product', table_name='pantry_entry', postgresql_where=sa.text('ref is not null'))
    op.drop_index(op.f('ix_pantry_entry_product_key'), table_name='pantry_entry')
    op.drop_table('pantry_entry')
    op.drop_table('meal_plan')
    op.drop_table('wolt_order')
    op.drop_table('recipe')
    op.drop_table('product')
    # ### end Alembic commands ###
