"""week menu: menus per user, the meals a recipe fits, orders placed for a menu

Revision ID: 525a0bd9e5e5
Revises: 72cd0f3e9a80
Create Date: 2026-10-01 12:20:03.944692

Comes after the recipe book: prod got that one first, so its revision is already stamped
there. recipe.meals is filled here from the same book, matched by slug; recipes added
through the API since then get lunch and dinner.
"""
import json
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '525a0bd9e5e5'
down_revision: Union[str, Sequence[str], None] = '72cd0f3e9a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

BOOK = Path(__file__).resolve().parents[1] / "data" / "recipe_book.json"

recipe = sa.table("recipe", sa.column("slug", sa.String), sa.column("meals", postgresql.ARRAY(sa.String)))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('draft', 'awaiting_order', 'ordered')", name=op.f('ck_week_menu_status')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_week_menu_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_week_menu')),
    sa.UniqueConstraint('user_id', 'start', name=op.f('uq_week_menu_user_id_start'))
    )
    op.create_index(op.f('ix_week_menu_user_id'), 'week_menu', ['user_id'], unique=False)
    op.add_column('recipe', sa.Column('meals', postgresql.ARRAY(sa.String(length=16)), server_default='{lunch,dinner}', nullable=False))
    # an empty list: not picked into week menus on its own (side salads, desserts)
    op.create_check_constraint(op.f('ck_recipe_meals'), 'recipe', "meals <@ array['breakfast', 'lunch', 'dinner']::varchar[]")
    book = json.loads(BOOK.read_text(encoding="utf-8"))
    op.get_bind().execute(
        recipe.update().where(recipe.c.slug == sa.bindparam("b_slug"))
        .values(meals=sa.bindparam("b_meals", type_=postgresql.ARRAY(sa.String))),
        [{"b_slug": r["slug"], "b_meals": r["meals"]} for r in book["recipes"]])
    op.add_column('wolt_order', sa.Column('week_menu_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wolt_order_week_menu_id'), 'wolt_order', ['week_menu_id'], unique=False)
    op.create_foreign_key(op.f('fk_wolt_order_week_menu_id_week_menu'), 'wolt_order', 'week_menu', ['week_menu_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_wolt_order_week_menu_id_week_menu'), 'wolt_order', type_='foreignkey')
    op.drop_index(op.f('ix_wolt_order_week_menu_id'), table_name='wolt_order')
    op.drop_column('wolt_order', 'week_menu_id')
    op.drop_constraint(op.f('ck_recipe_meals'), 'recipe', type_='check')
    op.drop_column('recipe', 'meals')
    op.drop_index(op.f('ix_week_menu_user_id'), table_name='week_menu')
    op.drop_table('week_menu')
    # ### end Alembic commands ###
