"""wolt sync log

Revision ID: be2660bdc370
Revises: e5d5bf9e6564
Create Date: 2026-10-01 16:01:21.243109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be2660bdc370'
down_revision: Union[str, Sequence[str], None] = 'e5d5bf9e6564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wolt_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='button', nullable=False),
    sa.Column('orders_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('orders_imported', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pantry_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wolt_sync_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wolt_sync_log')
    # ### end Alembic commands ###
