"""recipe category and week template

Revision ID: c8cd64f9f352
Revises: 7c770aab3e41
Create Date: 2026-10-01 12:31:32.905022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cd64f9f352'
down_revision: Union[str, Sequence[str], None] = '7c770aab3e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_template',
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(length=16), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Numeric(asdecimal=False), server_default='1', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("meal in ('breakfast', 'lunch', 'dinner')", name=op.f('ck_week_template_meal')),
    sa.CheckConstraint('day_offset between 0 and 6', name=op.f('ck_week_template_day_offset')),
    sa.CheckConstraint('multiplier > 0', name=op.f('ck_week_template_multiplier_positive')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_week_template_recipe_id_recipe'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('day_offset', 'meal', name=op.f('pk_week_template'))
    )
    op.add_column('recipe', sa.Column('category', sa.String(length=16), server_default='main', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f('ck_recipe_category'), 'recipe', "category in ('breakfast', 'soup', 'main', 'salad', 'snack', 'dessert')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'category')
    op.drop_table('week_template')
    # ### end Alembic commands ###
